const DEFAULT_USER_LOCATION = "US";
const VIDEOS_KEY = "videos";
const BASE_URL_TO_FETCH_VIDEOS = "/videos";
const BASE_URL_TO_YOUTUBE_VIDEOS = "https://www.youtube.com/embed/";

export { DEFAULT_USER_LOCATION, VIDEOS_KEY, BASE_URL_TO_FETCH_VIDEOS, BASE_URL_TO_YOUTUBE_VIDEOS };