const DEFAULT_USER_LOCATION = "US";
const COUNTRY_DATA_KEY = "countryData";
const BASE_URL_TO_FETCH_VIDEOS = "/videos";
const BASE_URL_TO_YOUTUBE_VIDEOS = "https://www.youtube.com/embed/";

export { DEFAULT_USER_LOCATION, COUNTRY_DATA_KEY, BASE_URL_TO_FETCH_VIDEOS, BASE_URL_TO_YOUTUBE_VIDEOS };